batchSize: 5000

rabbitServer: "rabbit.abelyaev.net"
rabbitPort: 5671
rabbitConnectionTimeout: 300
rabbitUser: "worker"
rabbitPassword: "password"
rabbitVhost: "/consumer"
rabbitClientCert: "cert.pem"
rabbitClientKeyPassPhrase: "PassPhrase"
rabbitCaCert: "cacert.pem"

storageUrl: "https://abelyaev.net:9443/"
storageClientCert: "storage-client-01.pem"
storageCaCert: "storage-server-ca.crt"
